//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpegitimKampı301EFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lokation
    {
        public int LokationId { get; set; }
        public string LokationCity { get; set; }
        public string LokationCountry { get; set; }
        public Nullable<byte> LokationCapacitiy { get; set; }
        public Nullable<decimal> LokationPrice { get; set; }
        public string DayNighit { get; set; }
        public Nullable<int> GuideId { get; set; }
    
        public virtual TblGuide TblGuide { get; set; }
    }
}
